name: Build Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.4  # Replace with the Go version you are using

    - name: Install dependencies
      run: |
        cd go
        go mod tidy

    - name: Build
      run: |
        cd go
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o sysutil-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sysutil-${{ matrix.goos }}-${{ matrix.goarch }}
        path: go/sysutil-${{ matrix.goos }}-${{ matrix.goarch }}

